# Generated by Django 6.0.4 on 2026-04-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_category_created_at_category_updated_at_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(fields=('product', 'image'), name='unique_product_image'),
        ),
    ]
