# Generated by Django 6.0.4 on 2026-04-18 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_productimage_unique_product_image'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productimage',
            name='unique_product_image',
        ),
    ]
